// ==========================================================
// DOCENT — Markdown → Print-friendly HTML for PDF export
// Zero dependencies — converts markdown to styled HTML string
// ==========================================================

/**
 * Convert markdown text to a standalone HTML document string
 * suitable for printing / saving as PDF via window.print().
 */
export function markdownToHtml(markdown: string, title?: string): string {
  let html = markdown;

  // --- Block-level transforms (order matters) ---

  // Horizontal rules
  html = html.replace(/^---+$/gm, '<hr/>');

  // Headers
  html = html.replace(/^#### (.+)$/gm, '<h4>$1</h4>');
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');

  // Tables — convert pipe-delimited markdown tables to HTML
  html = convertTables(html);

  // Blockquotes (multi-line support)
  html = html.replace(/(^> .+\n?)+/gm, (match) => {
    const inner = match.replace(/^> /gm, '').trim();
    return `<blockquote>${processInline(inner)}</blockquote>\n`;
  });

  // Unordered lists
  html = html.replace(/(^- .+\n?)+/gm, (match) => {
    const items = match.trim().split('\n').map(line => `<li>${processInline(line.replace(/^- /, ''))}</li>`).join('\n');
    return `<ul>${items}</ul>\n`;
  });

  // Paragraphs — wrap remaining bare lines
  const lines = html.split('\n');
  const result: string[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      result.push('');
    } else if (
      trimmed.startsWith('<h') || trimmed.startsWith('<hr') ||
      trimmed.startsWith('<table') || trimmed.startsWith('<ul') ||
      trimmed.startsWith('<li') || trimmed.startsWith('<blockquote') ||
      trimmed.startsWith('</') || trimmed.startsWith('<tr') ||
      trimmed.startsWith('<thead') || trimmed.startsWith('<tbody')
    ) {
      result.push(line);
    } else {
      result.push(`<p>${processInline(trimmed)}</p>`);
    }
  }
  html = result.join('\n');

  // Build full document
  const docTitle = title || 'Deep Analysis Report';
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>${docTitle}</title>
<style>
  @page { margin: 1.5cm 2cm; size: A4; }
  * { box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1a1a1a;
    max-width: 100%;
    margin: 0;
    padding: 0;
  }
  h1 { font-size: 18pt; margin: 0 0 4pt; color: #1a1a1a; border-bottom: 2px solid #D4A853; padding-bottom: 6pt; }
  h2 { font-size: 16pt; margin: 16pt 0 6pt; color: #1a1a1a; border-bottom: 1px solid #ddd; padding-bottom: 4pt; }
  h3 { font-size: 13pt; margin: 14pt 0 6pt; color: #333; }
  h4 { font-size: 11pt; margin: 10pt 0 4pt; color: #444; font-weight: 600; }
  p { margin: 4pt 0; }
  strong { font-weight: 700; }
  em { font-style: italic; }
  code { font-family: 'Consolas', 'Courier New', monospace; font-size: 10pt; background: #f5f5f5; padding: 1pt 3pt; border-radius: 2pt; }
  hr { border: none; border-top: 1px solid #ccc; margin: 12pt 0; }
  blockquote {
    margin: 6pt 0;
    padding: 6pt 12pt;
    border-left: 3px solid #D4A853;
    background: #faf8f3;
    font-size: 10.5pt;
    page-break-inside: avoid;
  }
  blockquote p { margin: 2pt 0; }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 8pt 0;
    font-size: 10pt;
    page-break-inside: avoid;
  }
  th {
    background: #f0f0f0;
    font-weight: 700;
    text-align: left;
    padding: 5pt 8pt;
    border: 1px solid #ccc;
  }
  td {
    padding: 4pt 8pt;
    border: 1px solid #ddd;
    vertical-align: top;
  }
  tr:nth-child(even) td { background: #fafafa; }
  ul { margin: 4pt 0; padding-left: 20pt; }
  li { margin: 2pt 0; }
  .date { font-size: 9pt; color: #888; margin-bottom: 12pt; }
  .footer { margin-top: 20pt; font-size: 9pt; color: #888; border-top: 1px solid #ddd; padding-top: 6pt; }
  @media print {
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    blockquote { background: #faf8f3 !important; border-left-color: #D4A853 !important; }
    th { background: #f0f0f0 !important; }
  }
</style>
</head>
<body>
<div class="date">Exported ${date} — Docent by Symbiont AI</div>
${html}
<div class="footer">Generated by Docent — AI Presenter by Symbiont AI Cognitive Labs</div>
</body>
</html>`;
}

/** Process inline markdown: bold, italic, code, links */
function processInline(text: string): string {
  return text
    // Inline code
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
}

/** Convert pipe-delimited markdown tables to HTML tables */
function convertTables(text: string): string {
  // Match table blocks: header row, separator row, data rows
  const tableRegex = /(\|.+\|)\n(\|[-| :]+\|)\n((\|.+\|\n?)+)/g;

  return text.replace(tableRegex, (_match, headerLine: string, _sepLine: string, bodyBlock: string) => {
    const headers = headerLine.split('|').slice(1, -1).map((h: string) => h.trim());
    const bodyRows = bodyBlock.trim().split('\n').map((row: string) =>
      row.split('|').slice(1, -1).map((cell: string) => cell.trim())
    );

    const thead = `<thead><tr>${headers.map((h: string) => `<th>${processInline(h)}</th>`).join('')}</tr></thead>`;
    const tbody = `<tbody>${bodyRows.map((row: string[]) =>
      `<tr>${row.map((cell: string) => `<td>${processInline(cell)}</td>`).join('')}</tr>`
    ).join('\n')}</tbody>`;

    return `<table>${thead}\n${tbody}</table>\n`;
  });
}
